version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "waf-api-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1itbpbaza7j6c"
s3_prefix = "waf-api-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
